### ISSUE TITLE
Upload file

### ISSUE THREAD

**Issue by dungphanxuan** [cliff363825/yii2-kindeditor#2]
Hello, i use this extension in my app. So now i want to upload image. How can i use in my app. Thank

**Comment by cliff363825** [comment]
1. create a controller extends \cliff363825\kindeditor\controllers\KindEditorBaseController.
2. overide actionUpload method if you need.
3. configurate KindEditor Widget clientOptions.

code for example:

``` php
class DemoController extends \cliff363825\kindeditor\controllers\KindEditorBaseController{
    public function actionUpload()
    {
        // override this method if you need.
        parent::actionUpload(); // TODO: Change the autogenerated stub

    }
}
```

configurate KindEditor Widget clientOptions

``` php
KindEditorWidget::widget([
        'clientOptions'=>[
            // bla
            'uploadJson'=>Url::to(['/demo/upload']), // note:  '/demo/upload' must be a valid route.
            // bla....
        ],
    ]);
```

**Comment by dungphanxuan** [comment]
Hello @cliff363825 , i folow your Instruction and config in my app and it run !!!
Thank you!
