### ISSUE TITLE
大神，图片上传时提示上传目录不存在怎么解决？

### ISSUE THREAD

**Issue by tianqiongbaiyang** [cliff363825/yii2-kindeditor#6]
![default](https://cloud.githubusercontent.com/assets/26560505/24337775/cd1587a4-12d2-11e7-92f7-3948dbf2345b.png)
actions（）方法：'upload' => [
                'class' => '\cliff363825\kindeditor\KindEditorUploadAction',
                'maxSize' => 2097152,
            ],
views视图：<?= \cliff363825\kindeditor\KindEditorWidget::widget([
    'name' => 'content',
    'options' => [], // html attributes
    'clientOptions' => [
        'width' => '680px',
        'height' => '350px',
        'themeType' => 'default', // optional: default, simple, qq
        'langType' => \cliff363825\kindeditor\KindEditorWidget::LANG_TYPE_ZH_CN, // optional: ar, en, ko, ru, zh-CN, zh-TW
        'uploadJson'=>Url::to(['test/upload'])
    ],
]); ?>

**Comment by cliff363825** [comment]
@tianqiongbaiyang ，请尝试在 你的index.php同级目录下新建一个 uploads的文件夹

**Comment by tianqiongbaiyang** [comment]
可以了，谢谢！
